spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
scheduler:
  gift: "0 0 0 1/1 * *"
  meal: "0 0 0 1 3 *"
